{"name": "Wrong Login Credentials Validation", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Locator.text_content: Target page, context or browser has been closed\nCall log:\n  - waiting for locator(\"//p[@class='oxd-text oxd-text--p oxd-alert-content-text']\")", "trace": "self = <testCases.login_test.TestLoginValidation object at 0x000001A79BE1B610>\npage_with_screenshot = <Page url='https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index'>\n\n    @allure.story(\"Login Function Validations\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.title(\"Wrong Login Credentials Validation\")\n    @pytest.mark.ui\n    @pytest.mark.critical\n    def test_wrong_login(self, page_with_screenshot):\n        \"\"\"Test Payer Name Field Validation\"\"\"\n        login_page = LoginPage(page_with_screenshot)\n        try:\n            with allure.step(\"Filling Username\"):\n                login_page.fill_username(\"Admin\")\n    \n            with allure.step(\"Filling Password\"):\n                login_page.fill_password(\"admin123\")\n    \n            with allure.step(\"Clicking Login Button\"):\n                login_page.click_login()\n    \n            with allure.step(\"Verifying error message \"):\n                expected_text = \"Invalid credentials\"\n    \n                try:\n>                   actual_text = login_page.get_error_message_text()\n\ntestCases\\login_test.py:66: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npageObjects\\loginpage.py:58: in get_error_message_text\n    return self.error_message.text_content()\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:17621: in text_content\n    self._sync(self._impl_obj.text_content(timeout=timeout))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_locator.py:616: in text_content\n    return await self._frame.text_content(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:613: in text_content\n    return await self._channel.send(\"textContent\", locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000001A79BFEB4D0>, cb = <function Channel.send.<locals>.<lambda> at 0x000001A79C2D5260>, is_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TargetClosedError: Locator.text_content: Target page, context or browser has been closed\nE           Call log:\nE             - waiting for locator(\"//p[@class='oxd-text oxd-text--p oxd-alert-content-text']\")\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: TargetClosedError"}, "description": "Test Payer Name Field Validation", "steps": [{"name": "Filling Username", "status": "passed", "start": 1743512623988, "stop": 1743512624423}, {"name": "Filling Password", "status": "passed", "start": 1743512624423, "stop": 1743512624751}, {"name": "Clicking Login Button", "status": "passed", "start": 1743512624751, "stop": 1743512626119}, {"name": "Verifying error message ", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TargetClosedError: Locator.text_content: Target page, context or browser has been closed\nCall log:\n  - waiting for locator(\"//p[@class='oxd-text oxd-text--p oxd-alert-content-text']\")\n\n", "trace": "  File \"C:\\Users\\Bhargava\\PycharmProjects\\DemoProject\\testCases\\login_test.py\", line 66, in test_wrong_login\n    actual_text = login_page.get_error_message_text()\n  File \"C:\\Users\\Bhargava\\PycharmProjects\\DemoProject\\pageObjects\\loginpage.py\", line 58, in get_error_message_text\n    return self.error_message.text_content()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Bhargava\\PycharmProjects\\DemoProject\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 17621, in text_content\n    self._sync(self._impl_obj.text_content(timeout=timeout))\n    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Bhargava\\PycharmProjects\\DemoProject\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ~~~~~~~~~~~^^\n  File \"C:\\Users\\Bhargava\\PycharmProjects\\DemoProject\\.venv\\Lib\\site-packages\\playwright\\_impl\\_locator.py\", line 616, in text_content\n    return await self._frame.text_content(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n    )\n    ^\n  File \"C:\\Users\\Bhargava\\PycharmProjects\\DemoProject\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 613, in text_content\n    return await self._channel.send(\"textContent\", locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Bhargava\\PycharmProjects\\DemoProject\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<2 lines>...\n    )\n    ^\n  File \"C:\\Users\\Bhargava\\PycharmProjects\\DemoProject\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1743512626119, "stop": 1743512634512}], "attachments": [{"name": "Exception Details", "source": "bf307d29-05a0-4478-b64e-94c62cc97916-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "c35f19d0-747e-43e2-b26c-cdc46ff3c592-attachment.txt", "type": "text/plain"}], "start": 1743512623988, "stop": 1743512634522, "uuid": "33a707ec-c63a-4c8e-aa3a-b98c34748186", "historyId": "27649a8c536428e55be848daf347b996", "testCaseId": "27649a8c536428e55be848daf347b996", "fullName": "testCases.login_test.TestLoginValidation#test_wrong_login", "labels": [{"name": "story", "value": "Login Function Validations"}, {"name": "feature", "value": "Authentication"}, {"name": "epic", "value": "Orange HRM"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "critical"}, {"name": "tag", "value": "ui"}, {"name": "parentSuite", "value": "testCases"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLoginValidation"}, {"name": "host", "value": "SRS-CL-009"}, {"name": "thread", "value": "2580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.login_test"}]}